name: Pronto
on: [pull_request]

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: reviewdog/action-golangci-lint@82a29cf18d098bc46657b03195d7185dd96701ce
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "-v"
